/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YW2AmCKPAH4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { JSX, SVGProps } from "react"

export function Marketplace() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="flex items-center justify-between px-6 py-4 border-b bg-background">
        <Link href="#" className="flex items-center gap-2 font-semibold text-lg" prefetch={false}>
          <BriefcaseIcon className="h-6 w-6" />
          Idividuum
        </Link>
        <Button variant="outline" className="px-4 py-2 rounded-md">
          Login
        </Button>
      </header>
      <main className="flex-1 px-6 py-8">
        <div className="max-w-4xl mx-auto grid gap-8">
          <div className="grid gap-2">
            <h1 className="text-3xl font-bold">Live Offers</h1>
            <p className="text-muted-foreground">Browse and complete social media tasks to earn rewards.</p>
          </div>
          <div className="grid gap-4">
            <div className="bg-muted rounded-lg p-6 grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-0.5">
                    <p className="font-medium">Acme Inc</p>
                    <p className="text-sm text-muted-foreground">Twitter Engagement</p>
                  </div>
                </div>
                <Badge variant="secondary">$5 per task</Badge>
              </div>
              <div className="grid gap-2">
                <p>Like and follow our Twitter account to earn $5 per completion.</p>
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Expires in 7 days</p>
                </div>
                <Progress value={Math.floor(Math.random() * 101)} aria-label="Budget progress" />
                <div className="text-sm font-medium">{Math.floor(Math.random() * 101)}%</div>
              </div>
              <Button className="w-full">Apply</Button>
            </div>
            <div className="bg-muted rounded-lg p-6 grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-0.5">
                    <p className="font-medium">Globex Corporation</p>
                    <p className="text-sm text-muted-foreground">Instagram Engagement</p>
                  </div>
                </div>
                <Badge variant="secondary">$10 per task</Badge>
              </div>
              <div className="grid gap-2">
                <p>Like and follow our Instagram account to earn $10 per completion.</p>
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Expires in 14 days</p>
                </div>
                <Progress value={Math.floor(Math.random() * 101)} aria-label="Budget progress" />
                <div className="text-sm font-medium">{Math.floor(Math.random() * 101)}%</div>
              </div>
              <Button className="w-full">Apply</Button>
            </div>
            <div className="bg-muted rounded-lg p-6 grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>AC</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-0.5">
                    <p className="font-medium">Stark Industries</p>
                    <p className="text-sm text-muted-foreground">YouTube Engagement</p>
                  </div>
                </div>
                <Badge variant="secondary">$15 per task</Badge>
              </div>
              <div className="grid gap-2">
                <p>Subscribe to our YouTube channel and like 3 videos to earn $15 per completion.</p>
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-4 w-4 text-muted-foreground" />
                  <p className="text-sm text-muted-foreground">Expires in 30 days</p>
                </div>
                <Progress value={Math.floor(Math.random() * 101)} aria-label="Budget progress" />
                <div className="text-sm font-medium">{Math.floor(Math.random() * 101)}%</div>
              </div>
              <Button className="w-full">Apply</Button>
            </div>
          </div>
          <Button className="ml-auto">Post</Button>
        </div>
      </main>
    </div>
  )
}

function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CalendarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
